package com.tnt.entity;

import com.j256.ormlite.field.DatabaseField;

public class Account {

	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int accountId;
	@DatabaseField
	String accountName;
	@DatabaseField
	Double accountLimit;

	public Account() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @return the accountId
	 */
	public int getAccountId() {
		return accountId;
	}

	/**
	 * @param accountId
	 *            the accountId to set
	 */
	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	/**
	 * @return the accountName
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * @param accountName
	 *            the accountName to set
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * @return the accountLimit
	 */
	public Double getAccountLimit() {
		return accountLimit;
	}

	/**
	 * @param accountLimit
	 *            the accountLimit to set
	 */
	public void setAccountLimit(Double accountLimit) {
		this.accountLimit = accountLimit;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("accountId: ").append(accountId).append("  Account Name: ")
				.append(accountName).append("   Account Limit: ")
				.append(accountLimit);
		return sb.toString();
	}
}
