package com.tnt.entity;

import java.io.Serializable;
import com.j256.ormlite.field.DatabaseField;

public class Contact implements Serializable{

	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int contactId;
	@DatabaseField
	String contactName;

	public Contact() {
		// for ORMLite
	}

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    @Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Contact Id: ").append(contactId).append("  Contact Name: ")
				.append(contactName);
		return sb.toString();
	}

}