package com.tnt.entity;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;

public class GroupTransaction implements Serializable{
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int groupTransactionId;
	@DatabaseField(canBeNull = false, foreign = true)
	Transaction transaction;
	@DatabaseField(canBeNull = false, foreign = true)
	Contact contact;
	@DatabaseField
	double contactTransactionAmount;


	public GroupTransaction() {
		// TODO Auto-generated constructor stub
		// for ORMLite
	}


	/**
	 * @return the groupTransactionId
	 */
	public int getGroupTransactionId() {
		return groupTransactionId;
	}


	/**
	 * @param groupTransactionId the groupTransactionId to set
	 */
	public void setGroupTransactionId(int groupTransactionId) {
		this.groupTransactionId = groupTransactionId;
	}
	
	/**
	 * @return the transaction
	 */
	public Transaction getTransaction() {
		return transaction;
	}


	/**
	 * @param transaction the transaction to set
	 */
	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}


	/**
	 * @return the contact
	 */
	public Contact getContact() {
		return contact;
	}


	/**
	 * @param contact the contact to set
	 */
	public void setContact(Contact contact) {
		this.contact = contact;
	}


	/**
	 * @return the contactTransactionAmount
	 */
	public double getContactTransactionAmount() {
		return contactTransactionAmount;
	}


	/**
	 * @param contactTransactionAmount the contactTransactionAmount to set
	 */
	public void setContactTransactionAmount(double contactTransactionAmount) {
		this.contactTransactionAmount = contactTransactionAmount;
	}

	
}
