package com.tnt.entity;

import java.io.Serializable;
import com.j256.ormlite.field.DatabaseField;

public class Login implements Serializable {
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int loginId;
	@DatabaseField
	String loginUserName;
	@DatabaseField
	String loginPassword;
	@DatabaseField
	boolean isRememberChecked;
	
	public Login(){
		// default constructor for ORMLite
	}
	
	/**
	 * @return the loginId
	 */
	public int getLoginId() {
		return loginId;
	}
	/**
	 * @param loginId the loginId to set
	 */
	public void setLoginId(int loginId) {
		this.loginId = loginId;
	}
	/**
	 * @return the loginUserName
	 */
	public String getLoginUserName() {
		return loginUserName;
	}
	/**
	 * @param loginUserName the loginUserName to set
	 */
	public void setLoginUserName(String loginUserName) {
		this.loginUserName = loginUserName;
	}
	/**
	 * @return the loginPassword
	 */
	public String getLoginPassword() {
		return loginPassword;
	}
	/**
	 * @param loginPassword the loginPassword to set
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}
	/**
	 * @return the isRememberChecked
	 */
	public boolean isRememberChecked() {
		return isRememberChecked;
	}
	/**
	 * @param isRememberChecked the isRememberChecked to set
	 */
	public void setRememberChecked(boolean isRememberChecked) {
		this.isRememberChecked = isRememberChecked;
	}
	
	
}
