package com.tnt.entity;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;

public class PersonalTransaction implements Serializable{
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int personalTransactionId;
	@DatabaseField(canBeNull = false, foreign = true)
	Transaction transaction;
	@DatabaseField
	double transactionTotalAmount;


	public PersonalTransaction() {
		// TODO Auto-generated constructor stub
		// for ORMLite
	}
	
	/**
	 * @return the personalTransactionId
	 */
	public int getPersonalTransactionId() {
		return personalTransactionId;
	}

	/**
	 * @param personalTransactionId the personalTransactionId to set
	 */
	public void setPersonalTransactionId(int personalTransactionId) {
		this.personalTransactionId = personalTransactionId;
	}

	/**
	 * @return the transaction
	 */
	public Transaction getTransaction() {
		return transaction;
	}

	/**
	 * @param transaction the transaction to set
	 */
	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	/**
	 * @return the transactionTotalAmount
	 */
	public double getTransactionTotalAmount() {
		return transactionTotalAmount;
	}

	/**
	 * @param transactionTotalAmount the transactionTotalAmount to set
	 */
	public void setTransactionTotalAmount(double transactionTotalAmount) {
		this.transactionTotalAmount = transactionTotalAmount;
	}
}
