package com.tnt.entity;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;

public class Transaction implements Serializable{
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int transactionId;
	@DatabaseField(canBeNull = false, foreign = true)
	Account account;
	@DatabaseField
	String transactionName;
	@DatabaseField(canBeNull = false, foreign = true)
	TransactionType transactionType;
	@DatabaseField
	String transactionDate;
	@DatabaseField
	double transactionTotalAmount;
	@DatabaseField
	String ExpenseType;

	/**
	 * @return the account
	 */
	public Account getAccount() {
		return account;
	}

	/**
	 * @param account the account to set
	 */
	public void setAccount(Account account) {
		this.account = account;
	}

	/**
	 * @return the transactionType
	 */
	public TransactionType getTransactionType() {
		return transactionType;
	}

	/**
	 * @param transactionType the transactionType to set
	 */
	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	public Transaction() {
		// TODO Auto-generated constructor stub
		// for ORMLite
	}
	
	// all getters and setters
	
	/**
	 * @return the transactionId
	 */
	public int getTransactionId() {
		return transactionId;
	}

	/**
	 * @param transactionId the transactionId to set
	 */
	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}
	
	/**
	 * @return the transactionName
	 */
	public String getTransactionName() {
		return transactionName;
	}

	/**
	 * @param transactionName the transactionName to set
	 */
	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	/**
	 * @return the transactionDate
	 */
	public String getTransactionDate() {
		return transactionDate;
	}

	/**
	 * @param transactionDate the transactionDate to set
	 */
	public void setTransactionDate(String transactionDate) {
		this.transactionDate = transactionDate;
	}

	/**
	 * @return the transactionTotalAmount
	 */
	public double getTransactionTotalAmount() {
		return transactionTotalAmount;
	}

	/**
	 * @param transactionTotalAmount the transactionTotalAmount to set
	 */
	public void setTransactionTotalAmount(double transactionTotalAmount) {
		this.transactionTotalAmount = transactionTotalAmount;
	}

	/**
	 * @return the expenseType
	 */
	public String getExpenseType() {
		return ExpenseType;
	}

	/**
	 * @param expenseType the expenseType to set
	 */
	public void setExpenseType(String expenseType) {
		ExpenseType = expenseType;
	}
	

	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Transaction Id: ").append(transactionId).append("  Account Id: ")
				.append(account).append("Transaction Name: ").append(transactionName).append("  Transaction TypeId: ")
				.append(transactionType).append("Transaction Date: ").append(transactionDate).append("  Transaction Total Amount: ")
				.append(transactionTotalAmount).append("Expense Type: ").append(ExpenseType);
		return sb.toString();
	}

}
