package com.tnt.entity;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;

public class Transaction implements Serializable{
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int transactionId;
	@DatabaseField
	int accountId;
	@DatabaseField
	String transactionName;
	@DatabaseField
	int transactionTypeId;
	@DatabaseField
	String transactionDate;
	@DatabaseField
	double transactionTotalAmount;
	@DatabaseField
	String ExpenseType;

	public Transaction() {
		// TODO Auto-generated constructor stub
		// for ORMLite
	}
	
	// all getters and setters
	
	/**
	 * @return the transactionId
	 */
	public int getTransactionId() {
		return transactionId;
	}

	/**
	 * @param transactionId the transactionId to set
	 */
	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * @return the accountId
	 */
	public int getAccountId() {
		return accountId;
	}

	/**
	 * @param accountId the accountId to set
	 */
	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	/**
	 * @return the transactionName
	 */
	public String getTransactionName() {
		return transactionName;
	}

	/**
	 * @param transactionName the transactionName to set
	 */
	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	/**
	 * @return the transactionType
	 */
	public int getTransactionTypeId() {
		return transactionTypeId;
	}

	/**
	 * @param transactionType the transactionType to set
	 */
	public void setTransactionTypeId(int transactionTypeId) {
		this.transactionTypeId = transactionTypeId;
	}

	/**
	 * @return the transactionDate
	 */
	public String getTransactionDate() {
		return transactionDate;
	}

	/**
	 * @param transactionDate the transactionDate to set
	 */
	public void setTransactionDate(String transactionDate) {
		this.transactionDate = transactionDate;
	}

	/**
	 * @return the transactionTotalAmount
	 */
	public double getTransactionTotalAmount() {
		return transactionTotalAmount;
	}

	/**
	 * @param transactionTotalAmount the transactionTotalAmount to set
	 */
	public void setTransactionTotalAmount(double transactionTotalAmount) {
		this.transactionTotalAmount = transactionTotalAmount;
	}

	/**
	 * @return the expenseType
	 */
	public String getExpenseType() {
		return ExpenseType;
	}

	/**
	 * @param expenseType the expenseType to set
	 */
	public void setExpenseType(String expenseType) {
		ExpenseType = expenseType;
	}
	

	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Transaction Id: ").append(transactionId).append("  Account Id: ")
				.append(accountId).append("Transaction Name: ").append(transactionName).append("  Transaction TypeId: ")
				.append(transactionTypeId).append("Transaction Date: ").append(transactionDate).append("  Transaction Total Amount: ")
				.append(transactionTotalAmount).append("Expense Type: ").append(ExpenseType);
		return sb.toString();
	}

}
