package com.tnt.entity;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;

public class UserDetails implements Serializable {

	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int userId;
	@DatabaseField
	String firstName;
	@DatabaseField
	String lastName;
	@DatabaseField
	String emailId;
	@DatabaseField
	String username;
	@DatabaseField
	String password;

	public UserDetails() {
		// no arg constructor needed by ORMLite
	}

	/**
	 * @return the userId
	 */
	public int getUserId() {
		return userId;
	}

	/**
	 * @param userId
	 *            the userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @param firstName
	 *            the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @param lastName
	 *            the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return the emailId
	 */
	public String getEmailId() {
		return emailId;
	}

	/**
	 * @param emailId
	 *            the emailId to set
	 */
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *            the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("userId: ").append(userId).append("  First Name: ")
				.append(firstName).append("   Last Name: ").append(lastName);
		sb.append("   Email Id: ").append(emailId).append("   Username: ")
				.append(username).append("   Password: ").append(password);
		return sb.toString();
	}

}
